import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import styles from "./page.module.css";
import Header from "./(header)/page";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout = ({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) => {
    return (
        <html lang="en">
            <body className={`${styles.mainFont}`}>
                <Header />
                {children}
            </body>
        </html>
    );
};

export default RootLayout;
